ALTER TABLE users
  ADD COLUMN IF NOT EXISTS login VARCHAR(100) UNIQUE,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(20) UNIQUE,
  ADD COLUMN IF NOT EXISTS reset_code VARCHAR(10),
  ADD COLUMN IF NOT EXISTS reset_expires TIMESTAMPTZ;
